name: task_280398
description: Задание — Смена темы
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0" # Dart SDK version
  flutter: 3.10.3 # Fixed Flutter version

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2 # Пакет для создания архитектуры и сервис-сервис локатор
  get_it: ^7.6.7 # Пакет построения DI для уменьшения связности слоев архитектуры
  shared_preferences: ^2.2.2 # Пакет для взаимодействия с локальным хранилищем данных устройства
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SF Pro Display # шрифт используемый в примере в Figma
      fonts:
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Black.otf
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-BlackItalic.otf
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Bold.otf
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-BoldItalic.otf
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Heavy.otf
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-HeavyItalic.otf
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Light.otf
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-LightItalic.otf
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Medium.otf
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-MediumItalic.otf
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Regular.otf
          style: normal
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-RegularItalic.otf
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Semibold.otf
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-SemiboldItalic.otf
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Thin.otf
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-ThinItalic.otf
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Ultralight.otf