name: task_279830
description: Задание — Список покупок
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0" # Dart SDK version
  flutter: 3.10.3 # Fixed Flutter version

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: Sora
      fonts:
        - asset: fonts/Sora/Sora-Bold.ttf
        - asset: fonts/Sora/Sora-ExtraBold.ttf
        - asset: fonts/Sora/Sora-ExtraLight.ttf
        - asset: fonts/Sora/Sora-Light.ttf
        - asset: fonts/Sora/Sora-Medium.ttf
        - asset: fonts/Sora/Sora-Regular.ttf
          style: normal
        - asset: fonts/Sora/Sora-SemiBold.ttf
        - asset: fonts/Sora/Sora-Thin.ttf