name: task_285473
description: Задание — Валидация форм
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0" # Dart SDK version
  flutter: 3.10.3 # Fixed Flutter version

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  intl: ^0.18.0 # for DateTime
  provider: ^6.0.2 # Пакет для создания архитектуры и сервис-сервис локатор


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
