name: task_280049
description: Задание — Палитра цветов
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0" # Dart SDK version
  flutter: 3.10.3 # Fixed Flutter version

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2 # Пакет для создания архитектуры и сервис-сервис локатор

  get_it: ^7.6.7 # Пакет построения DI для уменьшения связности слоев архитектуры
  injectable: ^2.3.2 # Пакет кодогенерации DI по аннотациям (сделал и забыл)

  json_annotation: ^4.8.1 # Пакет для упрощения работы с DTO моделями
  collection: ^1.15.0 # Пакет расширения возможностей работы со списками

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.4.8 # Позволяет запускать кодогенерацию
  injectable_generator: ^2.1.5 # Генерирует по аннотациям DI приложения
  json_serializable: ^6.7.1 # Генерирует по описанию класса код для его сериализации и дессериализации

flutter:
  uses-material-design: true
  assets:
    - assets/colors.json # Путь к файлу данных карты цветов.
  fonts:
    - family: Ubuntu # шрифт используемый в примере в Figma
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Bold.ttf
        - asset: fonts/Ubuntu/Ubuntu-BoldItalic.ttf
        - asset: fonts/Ubuntu/Ubuntu-Italic.ttf
        - asset: fonts/Ubuntu/Ubuntu-Light.ttf
        - asset: fonts/Ubuntu/Ubuntu-LightItalic.ttf
        - asset: fonts/Ubuntu/Ubuntu-Medium.ttf
        - asset: fonts/Ubuntu/Ubuntu-MediumItalic.ttf
        - asset: fonts/Ubuntu/Ubuntu-Regular.ttf
          style: normal