name: task_283813
description: Задание — Визитка
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0" # Dart SDK version
  flutter: 3.10.3 # Fixed Flutter version

dependencies:
  flutter:
    sdk: flutter

  rive: ^0.12.3
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/rives/
  fonts:
    - family: Comforte
      fonts:
        - asset: fonts/comforte_regular.ttf
    - family: Ganesha
      fonts:
        - asset: fonts/ganesha_regular.ttf
    - family: Zarubka
      fonts:
        - asset: fonts/zarubka_regular.ttf
    - family: Cimero
      fonts:
        - asset: fonts/cimero_regular.otf
